# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Run script
        run: deno run -A json_to_cal.ts

      - name: Check for changes
        run: |
          if ! git diff --quiet; then
            echo "Changes detected"
          else
            echo "No changes detected"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add piletilevi.json
          git commit -m "Update calendar file"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
